election/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from election import views


urlpatterns = [
    url(r'^$', views.browse, name='browse'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/endorsements.json', views.get_endorsements,
        name='get-endorsements'),
    url(r'^api/tags.json', views.get_tags, name='get_tags'),
    url(r'^api/search.json', views.search_endorsers,
        name='search_endorsers'),
    url(r'^endorser/$', views.add_endorser,
        name='add-endorser'),
    url(r'^endorser/(?P<pk>\d+)/$', views.view_endorser,
        name='view-endorser'),
    url(r'^endorser/(?P<pk>\d+)/add-account$',
        views.add_account, name='add-account'),
    url(r'^endorser/(?P<pk>\d+)/add-endorsement$',
        views.add_endorsement, name='add-endorsement'),
    url(r'^endorsers/random$',
        views.random_endorser, name='random-endorser'),
    url(r'^progress/wikipedia$',
        views.progress_wikipedia, name='progress-wikipedia'),
    url(r'^progress/wikipedia/(?P<slug>[^/]+)/missing$',
        views.progress_wikipedia_missing, name='progress-wikipedia-missing'),
    url(r'^progress/wikipedia/(?P<slug>[^/]+)/(?P<mode>\w+)$',
        views.progress_wikipedia_list, name='progress-wikipedia-list'),
    url(r'^progress/tagging$', views.progress_tagging,
        name='progress-tagging'),
    url(r'^progress/twitter$', views.progress_twitter,
        name='progress-twitter'),
    url(r'^confirm/endorsements$',
        views.confirm_endorsements, name='confirm-endorsements'),
    url(r'^confirm/endorsements/(?P<pk>\d+)', views.confirm_endorsement,
        name='confirm-endorsement'),
    url(r'^confirm/newspapers$', views.confirm_newspapers,
        name='confirm-newspapers'),
    url(r'^confirm/newspapers/(?P<pk>\d+)', views.confirm_newspaper,
        name='confirm-newspaper'),
    url(r'^stats/states$', views.stats_states, name='stats-states'),
    url(r'^stats/predictions$', views.stats_predictions,
        name='stats-predictions'),
    url(r'^stats/tags$', views.stats_tags, name='stats-tags'),
    url(r'^stats/charts$', views.charts, name='charts'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

endorsements/models.py
from __future__ import unicode_literals
import shutil

from django.db import models
from django.urls import reverse
import requests

from endorsements.utils import get_twitter_client


class Event(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()

    def __unicode__(self):
        return self.name


class Category(models.Model):
    is_exclusive = models.BooleanField(default=False)
    name = models.CharField(max_length=30)
    allow_personal = models.BooleanField(default=True)
    allow_org = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Tag(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    is_personal = models.BooleanField(default=True)
    category = models.ForeignKey(Category, null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def get_mode(self):
        allow_personal = self.category.allow_personal
        allow_org = self.category.allow_org
        if allow_personal and allow_org:
            return 'none'
        elif allow_personal:
            return 'personal'
        else:
            return 'organization'


class Endorser(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    is_personal = models.BooleanField(default=True)
    max_followers = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)
    missing_image = models.BooleanField(default=True)
    current_position = models.ForeignKey('Position', blank=True, null=True)

    class Meta:
        ordering = ['-max_followers']

    def __unicode__(self):
        return self.name

    def has_url(self):
        return bool(self.url)
    has_url.boolean = True

    def get_tags(self):
        return ' / '.join(tag.name for tag in self.tags.all())

    def get_current_endorsement(self):
        try:
            return self.endorsement_set.latest('quote')
        except Endorsement.DoesNotExist:
            pass

    def get_image(self):
        return '<img src="{url}" width="100" />'.format(
            url=self.get_image_url()
        )
    get_image.allow_tags = True

    def get_image_url(self):
        image_name = 'missing' if self.missing_image else self.pk
        return 'https://s3.amazonaws.com/endorsementdb.com/images/endorsers/%s.png' % image_name

    def needs_quotes(self):
        current_endorsement = self.get_current_endorsement()
        return not current_endorsement.quote.text
    needs_quotes.boolean = True

    def get_absolute_url(self):
        return reverse('view-endorser', args=[self.pk])


class AccountManager(models.Manager):
    def get_from_username(self, username, endorser=None):
        twitter_client = get_twitter_client()
        response = twitter_client.users.lookup(
            screen_name=username
        )

        for user in response:
            twitter_id = user['id_str']

            # Expand the URL to avoid the t.co/ version.
            url = user['url']
            entities = user.get('entities')
            if entities:
                url_data = entities.get('url')
                if url_data:
                    urls = url_data['urls']
                    if urls:
                        url = urls[0]['expanded_url'] or url

            try:
                account = self.get(twitter_id=twitter_id)
                account.url = url
                account.profile_image_url = user['profile_image_url']
                account.followers_count = user['followers_count']

                # If the endorser is set, update it.
                if endorser is not None:
                    account.endorser = endorser

                account.save()
            except Account.DoesNotExist:
                # Create the endorser, if not specified as an argument.
                if endorser is None:
                    endorser = Endorser.objects.create(
                        name=user['name'],
                        description=user['description'],
                        url=url,
                        is_personal=True,
                        max_followers=user['followers_count'],
                        missing_image=False,
                    )
                else:
                    endorser.missing_image = False

                    # We may need to update max_followers for the endorser.
                    if user['followers_count'] > endorser.max_followers:
                        endorser.max_followers = user['followers_count']

                    endorser.save()

                account = self.create(
                    twitter_id=twitter_id,
                    screen_name=user['screen_name'],
                    name=user['name'],
                    description=user['description'],
                    location=user['location'],
                    protected=user['protected'],
                    verified=user['verified'],
                    profile_image_url=user['profile_image_url'],
                    url=url,
                    followers_count=user['followers_count'],
                    friends_count=user['friends_count'],
                    statuses_count=user['statuses_count'],
                    endorser=endorser,
                )

                account.save_image_to_s3()

            return account


class Account(models.Model):
    objects = AccountManager()

    twitter_id = models.CharField(max_length=20, primary_key=True)

    screen_name = models.CharField(max_length=50)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)

    protected = models.BooleanField()
    verified = models.BooleanField()

    profile_image_url = models.URLField(max_length=300, null=True)
    url = models.URLField(max_length=300, blank=True, null=True)

    followers_count = models.PositiveIntegerField()
    friends_count = models.PositiveIntegerField()
    statuses_count = models.PositiveIntegerField()

    last_updated = models.DateTimeField(auto_now=True)

    endorser = models.ForeignKey(Endorser)

    class Meta:
        ordering = ['-followers_count']

    def __unicode__(self):
        return '@{username} ({name})'.format(
            username=self.screen_name,
            name=self.name
        )

    def get_large_image(self):
        return self.profile_image_url.replace('normal', '400x400')

    def get_absolute_url(self):
        return "https://twitter.com/{username}".format(
            username=self.screen_name
        )

    def get_profile_image(self):
        return '<img src="%s" height="100" />' % self.profile_image_url
    get_profile_image.allow_tags = True
    get_profile_image.short_description = 'Profile image'

    def save_image_to_s3(self):
        """TODO"""
        import boto
        s3_connection = boto.connect_s3()
        bucket = s3_connection.get_bucket('endorsementdb.com')

        url = self.get_large_image()

        response = requests.get(url, stream=True)
        with open('/tmp/profile_image.png', 'wb') as out_file:
            shutil.copyfileobj(response.raw, out_file)
            del response

        key = bucket.new_key('images/endorsers/%d.png' % self.endorser.pk)
        key.set_contents_from_filename(out_file.name)
        key.make_public()


class Candidate(models.Model):
    endorser_link = models.OneToOneField(Endorser)
    name = models.CharField(max_length=50)
    description = models.TextField()
    color = models.CharField(max_length=6)
    rgb = models.CharField(max_length=13)
    still_running = models.BooleanField(default=False)
    position = models.OneToOneField('Position', blank=True, null=True)

    def __unicode__(self):
        return self.name


class Source(models.Model):
    date = models.DateField(null=True, blank=True)
    url = models.URLField(unique=True, blank=True, max_length=300)
    name = models.CharField(max_length=100, default='')

    class Meta:
        ordering = ['url', '-date']

    def get_date_display(self):
        if self.date:
            return self.date.strftime('%b %d, %Y')

    def __unicode__(self):
        return "{url} on {date}".format(
            url=self.url,
            date=self.date,
        )


class Quote(models.Model):
    context = models.TextField(null=True, blank=True)
    text = models.TextField(blank=True, null=True)
    source = models.ForeignKey(Source)
    # Defaults to the date of the source, but can be overridden.
    date = models.DateField(null=True, blank=True)
    event = models.ForeignKey(Event, null=True, blank=True)

    def get_date_display(self):
        if self.date:
            return self.date.strftime('%b %d, %Y')

    def get_source_display(self):
        return '<a href="{url}">{name}</a>'.format(
            url=self.source.url,
            name=self.source.name or self.source.url[:30],
        )
    get_source_display.allow_tags = True

    def __unicode__(self):
        return self.text[:150]

    class Meta:
        ordering = ['date']

    def get_event_context(self):
        event = self.event
        if event:
            if self.date >= event.end_date:
                return 'After'
            elif self.date <= event.start_date:
                return 'Before'
            else:
                return 'During'
    get_event_context.short_description = 'Timing'

    def get_display(self):
        if self.context:
            if len(self.context) > 100:
                context = self.context[:100] + '...<br />'
            else:
                context = self.context + '<br />'
        else:
            context = ''

        if self.text:

endorsements/forms.py
from django import forms

from endorsements.models import Candidate, Endorsement, Source, Position, \
                                Tag, Event


class Html5DateInput(forms.DateInput):
    input_type = 'date'


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        exclude = ('name',)
        widgets = {
            'date': Html5DateInput(),
        }


class PersonalTagForm(forms.Form):
    tag = forms.ModelChoiceField(
        Tag.objects.filter(is_personal=True)
    )


class OrganizationTagForm(forms.Form):
    tag = forms.ModelChoiceField(
        Tag.objects.filter(is_personal=False)
    )


class TagFilterForm(forms.Form):
    filter_tags_show = forms.ModelMultipleChoiceField(
        Tag.objects.all(), required=False
    )
    filter_tags_hide = forms.ModelMultipleChoiceField(
        Tag.objects.all(), required=False
    )


class EndorsementForm(forms.Form):
    position = forms.ModelChoiceField(Position.objects.all())
    quote = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 1}),
        required=False,
    )
    context = forms.CharField(
        widget=forms.Textarea(attrs={
            'rows': 1,
            'placeholder': 'e.g., "In an editorial endorsement" (leave blank if no context is required)'
        }),
        required=False,
    )
    date = forms.DateField(widget=Html5DateInput)
    source_url = forms.URLField(
        widget=forms.TextInput(attrs={'placeholder': 'http://example.com'})
    )
    source_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'e.g., Politico'})
    )
    event = forms.ModelChoiceField(Event.objects.all(), required=False)


class EndorsementFormWithoutPosition(EndorsementForm):
    position = None
    source_name = forms.CharField(required=False)
    date = forms.DateField(widget=Html5DateInput, required=False)
    source_url = forms.URLField(required=False)


class EndorserForm(forms.Form):
    name = forms.CharField(max_length=100)
    description = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4}),
        required=False,
    )
    url = forms.URLField(required=False)
    twitter_username_1 = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'placeholder': '@username1'}),
        required=False
    )
    twitter_username_2 = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'placeholder': '@username1'}),
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        Tag.objects.all(), required=False
    )
    is_personal = forms.BooleanField(required=False)

endorsements/templates/add_endorser_snippet.html
{% if request.user.is_staff %}
<form class="ui fluid action input" method="post" action="{% url 'add-endorser' %}">
    <input type="text" placeholder="Username" name="username" />
    <button type="submit" class="ui green icon button">
        <i class="user icon"></i>
    </button>
    {% csrf_token %}
</form>
{% endif %}

endorsements/templates/endorsements_snippet.html
{% if endorsements.count %}
<div class="ui fluid accordion">
{% for endorsement in endorsements %}
    <div class="{% if forloop.first %}active {% endif %}title">
        <i class="dropdown icon"></i>

        <div class="ui {{ endorsement.position.colour }} label">
            {% if forloop.first %}
            {{ endorsement.position.get_present_display }}
            {% else %}
            {{ endorsement.position.get_past_display }}
            {% endif %}
        </div>

        as of
        {% with quote=endorsement.quote %}
        {{ quote.date }}
    </div>
    <div class="content">
        <blockquote cite="{{ quote.source.url }}">
            {% with event_context=quote.get_event_context %}
            {% if event_context %}
            <p><em>[{{ event_context }} {{ quote.event }}]</em></p>
            <br /><br />
            {% endif %}
            {% endwith %}
            {% if quote.context %}
            <p><em>[{{ quote.context }}]</em></p>
            <br /><br />
            {% endif %}
            <p>{{ quote.text }}</p>
            <footer>
                <cite>
                    &mdash;
                    <a href="{{ quote.source.url }}">
                        {{ quote.source.name }}
                        <i class="external link icon"></i>
                    </a>
                    {% if quote.date != quote.source.date %}
                    (published {{ quote.source.date }})
                    {% endif %}
                    {% if request.user.is_staff %}
                    <a href="{% url 'admin:endorsements_quote_change' quote.pk %}"
                       class="ui mini blue icon button">
                        <i class="edit icon"></i>
                    </a>
                    {% endif %}
                </cite>
            </footer>
        </blockquote>
    </div>
    {% endwith %}
{% endfor %}
</div>
{% else %}
    {% if endorser.candidate %}
        <h3>Current candidate</h3>
    {% else %}
        <h3>No endorsements yet</h3>
    {% endif %}
{% endif %}

endorsements/templates/random_endorser.html
{% extends "base.html" %}

{% block title %}Random Endorser{% endblock %}

{% block buttons %}
<a class="ui blue icon button"
   href="{% url 'random-endorser' %}">
    <i class="shuffle icon"></i>
    Another random endorser
</a>
{% endblock %}

{% block content %}

<div class="ui horizontally divided grid">
    <div class="six wide column">
        <div class="ui header">
            {{ endorser.name }}
            {% if not endorser.is_personal %}
            <div class="ui black label">Organization</div>
            {% endif %}
            {% if endorser.url %}
            <div class="sub header">
                {{ endorser.url|urlize }}
            </div>
            {% endif %}
        </div>

        {% if endorser.description %}
        <p>
            {{ endorser.description }}
        </p>
        {% endif %}

        {% include "accounts_snippet.html" with accounts=endorser.account_set.all compact=True %}
    </div>
    <div class="ten wide column">
        {% with endorsements=endorser.endorsement_set.all %}
        {% if endorsements.count %}
        {% include "endorsements_snippet.html" with endorsements=endorsements compact=True %}
        {% endif %}
        {% endwith %}
    </div>
</div>

{% endblock %}

endorsements/templates/search_endorsers_snippet.html
{% verbatim %}
<div id="search">
    <div class="ui fluid vertical menu">
        <div class="item">
            <div class="ui icon input">
                <i class="search icon"></i>
                <input type="text" placeholder="Search ..."
                       v-model="input"
                       @keyup.up="shift_index(-1)"
                       @keyup.down="shift_index(1)"
                       @keypress.enter="show_endorser" />
            </div>
        </div>
        <a v-for="(endorser, i) in endorsers"
           :href="'/endorser/' + endorser.pk"
           class="item" :class="{active: i == active_index}">
            <strong>{{ endorser.name }}</strong>
        </a>
    </div>
</div>
{% endverbatim %}

endorsements/templates/tags_index.html
{% extends "base.html" %}

{% block breadcrumbs %}
<a class="section" href="{% url 'index' %}">Home</a>
<i class="right angle icon divider"></i>
Tags
{% endblock %}

{% block title %}
Endorsements by tag
{% endblock %}

{% block content %}
<table class="ui celled padded table">
    <thead>
        <tr class="first-row">
            <th style="width: 14%">Tag</th>
            {% for candidate in candidates %}
            <th data-rgb="{{ candidate.rgb }}"
                class="candidate-cell"
                style="background: rgb({{ candidate.rgb }}); color: #fff; width: 14%">
                {{ candidate }}
            </th>
            {% endfor %}
            <th style="background: #767676; color: #fff">Other</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr>
            <td>
                <div class="ui header">
                    {{ category.name }}
                </div>
                {{ category.num_tagged }} tagged
                ({{ category.percent_reporting|floatformat }}%)
            </td>
            {% for candidate in category.candidates %}
            <td>
                {{ candidate.num_tagged }} tagged
                ({{ candidate.percent_reporting|floatformat }}%)
            </td>
            {% endfor %}
        </tr>
        {% for tag in category.tags %}
        <tr>
            <td>{{ tag.name }}</td>
            {% for candidate in tag.candidates %}
            <td>
                {{ candidate.num_tagged }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% endblock %}